#!/usr/bin/env bash
# Publish the Homebrew cask that installs the macOS .pkg (teraflock/flockd#47).
#
# goreleaser's own cask (homebrew_casks in .goreleaser.yaml) installs the
# two binaries straight from the tarball, which reintroduces the quarantine
# attribute the package exists to avoid; it cannot express a `pkg` stanza.
# So when the pkg leg is on, goreleaser skips its cask upload
# (skip_upload templated on TERAFLOCK_MACOS_PKG) and this script writes the
# cask instead. Casks are macOS-only, so the Linux tarballs goreleaser used
# to list are dropped: Linuxbrew never installed them anyway (README).
#
# Usage: publish-cask.sh <version> <pkg-path> [tap-dir]
#   Computes the package sha256, renders Casks/tera.rb, and commits it to
#   teraflock/homebrew-tap using TAP_GITHUB_TOKEN. With [tap-dir] it only
#   writes the file there (for a dry run / test).
set -euo pipefail
# shellcheck source=lib.sh
. "$(dirname "$0")/lib.sh"

version=${1:?usage: publish-cask.sh <version> <pkg-path> [tap-dir]}
pkg=${2:?}
tap_dir=${3:-}

[ -f "$pkg" ] || { log "ERROR: missing package $pkg"; exit 1; }
pkg_name=$(basename "$pkg")
sha=$(shasum -a 256 "$pkg" | awk '{print $1}')

render() {
  cat <<EOF
# Generated by scripts/release/publish-cask.sh in teraflock/flockd. DO NOT EDIT.
#
# Installs the notarized, stapled installer package rather than the bare
# binaries: files placed by an installer carry no quarantine attribute, so
# neither the install nor the daemon's first launch under launchd waits on
# a Gatekeeper dialog (teraflock/flockd#47). The package installs to
# /usr/local/bin, which is why this cask asks for your password once.
cask "tera" do
  version "$version"
  sha256 "$sha"

  url "https://github.com/teraflock/flockd/releases/download/v#{version}/$pkg_name"
  name "tera"
  desc "Teraflock node daemon + CLI — earn credits serving LLM inference on idle hardware"
  homepage "https://teraflock.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  depends_on macos: ">= :monterey"

  pkg "$pkg_name"

  uninstall pkgutil: "ai.teraflock.tera",
            launchctl: "dev.teraflock.flockd"

  caveats <<~EOS
    To join the mesh you need an invite from teraflock.ai — then:
      tera login      # opens the claim page in your browser
      tera up         # installs and starts the background service
      tera dashboard  # watch it earn
  EOS
end
EOF
}

if [ -n "$tap_dir" ]; then
  mkdir -p "$tap_dir/Casks"
  render >"$tap_dir/Casks/tera.rb"
  log "cask: wrote $tap_dir/Casks/tera.rb (dry run, not pushed)"
  exit 0
fi

: "${TAP_GITHUB_TOKEN:?TAP_GITHUB_TOKEN (PAT with write access to teraflock/homebrew-tap) is required}"
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
# The token goes in the URL only for this clone; the remote is never
# printed and the directory is removed on exit.
git clone -q --depth 1 "https://x-access-token:${TAP_GITHUB_TOKEN}@github.com/teraflock/homebrew-tap.git" "$tmp/tap"
render >"$tmp/tap/Casks/tera.rb"
cd "$tmp/tap"
if git diff --quiet -- Casks/tera.rb; then
  log "cask: Casks/tera.rb already at $version; nothing to publish"
  exit 0
fi
git -c user.name="teraflock-release" -c user.email="release@teraflock.ai" \
  commit -q -m "Brew cask update for flockd version v${version} (installer package)" -- Casks/tera.rb
git push -q origin HEAD:main
log "cask: published Casks/tera.rb for v${version} -> $pkg_name"
