/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description The one unauthenticated management route: `tera up`, service managers, and the desktop app probe it before they hold a token.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Node status snapshot */
        get: operations["getStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Model catalog merged with local state */
        get: operations["getCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Locally installed models */
        get: operations["listModels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/{id}/pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pin or unpin a model (pinned models are never LRU-evicted) */
        post: operations["pinModel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/{id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start downloading a catalog model in the background
         * @description 202 when a download starts (or is already in flight); 200 when the model is already cached and ready. Progress streams over `/api/v1/events` as `model_progress` and shows in `received_bytes` on the model list.
         */
        post: operations["startModelDownload"];
        /** Cancel an in-flight download (the .partial file is kept for resume) */
        delete: operations["cancelModelDownload"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/{id}/load": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Load a model into the serving runtime
         * @description Synchronous — llama-server startup takes seconds and the caller wants the verdict. Downloads first if the artifact isn't cached.
         */
        post: operations["loadModel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/{id}/unload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unload a model from the runtime (the artifact stays cached) */
        post: operations["unloadModel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/{id}/default": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Serve this model when a request names none (must be loaded)
         * @description Only a chat model can be the default: a decision or embedding model is refused with `400`. With no chat model loaded the node has no default (`status.default_model` is empty).
         */
        post: operations["setDefaultModel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a model from disk (and unload it if loaded) */
        delete: operations["deleteModel"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/earnings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Earnings (ledger-backed when enrolled, else a labelled estimate) */
        get: operations["getEarnings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/limits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live governor limits */
        get: operations["getLimits"];
        /**
         * Update governor limits
         * @description Applies live and persists to the daemon-owned `<data_dir>/limits.toml` overlay; the operator's config.toml is never rewritten.
         */
        put: operations["updateLimits"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent daemon log entries (ring buffer) */
        get: operations["getLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/enroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enroll (or re-enroll) this node with the coordinator
         * @description Submits a claim code to the running daemon: enrollment plus a live tunnel (re)start, no restart required. Re-enrollment — needed when the mesh CA rotates — is only possible through this route; the startup path ignores claim codes while credentials exist.
         */
        post: operations["enrollNode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recent node activity (downloads, loads, evictions, declines)
         * @description The last 200 things the daemon did to its model store and runtimes, newest first, including everything the mesh did on the operator's behalf. In memory only; cleared on restart.
         */
        get: operations["getActivity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What the node is doing right now, and what it did recently
         * @description The live activity view: per loaded model the requests in flight,
         *     every in-flight request (kind, origin, elapsed, tokens so far),
         *     model operations that use the machine without a request (a runtime
         *     starting, a download), and the last finished requests (a bounded
         *     in-memory list of the last 200, newest first) — enough to answer "what was
         *     that GPU spike two minutes ago".
         *
         *     Facts only, never content: no prompt, no output, no error text and
         *     no identifier from outside the node (`id` is a counter local to
         *     this daemon process, there to match `request_started` /
         *     `request_finished` events). A request appears once it has passed
         *     admission and reached the runtime; one refused before that (node
         *     yielded, unknown model) did no work and is not listed.
         *
         *     Live updates: the `request_started` and `request_finished` SSE
         *     events carry the same objects, and every `status` event carries
         *     `activity` (the `models` and `operations` parts).
         */
        get: operations["getRequests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/update/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run a version check now
         * @description Fetches the version feed immediately (the daemon otherwise checks on startup and hourly) and returns the result.
         */
        post: operations["checkUpdate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live daemon events (SSE)
         * @description `text/event-stream`. Event types:
         *     - `status`: a full Status snapshot — every 2s, and immediately on
         *       governor state transitions and after enrollment.
         *     - `model_progress`: `{model, received_bytes, total_bytes}` during
         *       downloads (throttled).
         *     - `models_changed`: `{model, change}` where change is
         *       downloaded|loading|loaded|load_failed|unloaded|default, or
         *       `{change: catalog}` when a refreshed catalog differs from the one
         *       held. `loading` is a runtime starting (weights being read into
         *       memory); it ends with `loaded` or `load_failed`.
         *     - `request_started`: one InflightRequest when a request reaches a
         *       runtime (`elapsed_ms` 0, `tokens` 0).
         *     - `request_finished`: one FinishedRequest when it ends (same `id`).
         *     - `model_assignment`: `{model, state, error}` as a coordinator
         *       placement moves through assigned|downloading|ready|cached|
         *       declined|failed|evicted.
         *     - `activity`: one ActivityEvent as it happens (same rows as
         *       `GET /api/v1/activity`).
         *     - `update_available`: the Update object when a version check finds
         *       a newer release (once per discovered version).
         *     - `log` (only with `?logs=1`): one LogEntry per line as logged.
         *
         *     EventSource cannot send headers, so this route additionally accepts
         *     the bearer token as `?token=`. Hand-written handler — documented
         *     here, excluded from codegen.
         */
        get: operations["getEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OpenAI-compatible model list */
        get: operations["openaiListModels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/completions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * OpenAI-compatible chat completions (streaming supported)
         * @description Reasoning models: chain-of-thought is returned separately from the
         *     answer as `reasoning_content` (the DeepSeek / llama.cpp extension
         *     to the OpenAI shape) — on `choices[].message.reasoning_content` for
         *     non-streaming responses and on `choices[].delta.reasoning_content`
         *     for stream chunks — and is absent when the model produced none.
         *     Reasoning tokens count in `usage.completion_tokens`. Models whose
         *     thinking llama.cpp cannot parse still return it inline in `content`.
         */
        post: operations["openaiChatCompletions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/completions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** OpenAI-compatible text completions */
        post: operations["openaiCompletions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/embeddings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** OpenAI-compatible embeddings */
        post: operations["openaiEmbeddings"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/systemone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Typed decisions (TypeSafe-compatible System One API)
         * @description Answers bounded, typed questions about a `state` with a decision
         *     model (catalog `decision: true`) and returns probabilities instead
         *     of text: no tokens are generated and there is no streaming.
         *
         *     `model` is a concrete catalog id (`laya-q8_0`), a manifest id
         *     (`laya`) or its `flock/<id>` alias; the latter two resolve to the
         *     quant this node has loaded, else has on disk, else the manifest's
         *     first (the same names work on the chat routes). The response's
         *     `model` is always the concrete id.
         *
         *     Same contract as the mesh gateway's `POST /v1/systemone`
         *     (TypeSafe's request and response shapes):
         *
         *     - **Order is preserved.** `answers` come back in the order the
         *       `questions` were written, and every `probabilities` / `legend`
         *       object is in the order of the question's `criteria`. Options are
         *       shown to the model in the order written.
         *     - `legend` is rebuilt from the request's `criteria`.
         *     - `images` is rejected (`422`): no decision model in the catalog
         *       takes image input under llama.cpp yet.
         *     - Unknown top-level fields are ignored.
         *
         *     The model is loaded on demand when it is on disk but not in memory.
         */
        post: operations["systemOne"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                message: string;
                type: string;
                /** @description Machine-readable code where one exists (`model_not_found`). */
                code?: string;
            };
        };
        Ok: {
            ok: boolean;
        };
        Health: {
            ok: boolean;
            version: string;
        };
        Status: {
            /** @description Key fingerprint until enrolled; coordinator-assigned id after. */
            node_id: string;
            version: string;
            standalone: boolean;
            enrolled: boolean;
            /**
             * Format: date-time
             * @description Client-certificate expiry; present when enrolled.
             */
            cert_expires_at?: string;
            /** @description Why the last due client-certificate rotation failed; absent when rotation is not due or succeeded. The node keeps serving on the current certificate and leaves the mesh when it expires unless a later restart rotates it or the node is re-enrolled. */
            cert_rotation_error?: string;
            /** @description serving | starting | idle | no-model | yielded | paused-battery | paused-thermal | outside-schedule. `starting`: the default model is still being fetched or loaded; `idle`: nothing loaded but models are on disk (a placement or request loads one); `no-model`: nothing loaded and nothing on disk. */
            state: string;
            /** Format: int64 */
            uptime_seconds: number;
            default_model: string;
            activity: components["schemas"]["NodeActivity"];
            models_loaded: number;
            inflight: number;
            on_battery: boolean;
            /** Format: double */
            temp_celsius: number;
            hardware?: components["schemas"]["Hardware"];
            /** @description Accelerator backend of the llama-server build this node runs (`cuda12`, `rocm`, `vulkan`, `metal`, `cpu-avx2`, `cpu`): the first lane of the detection preference chain (cuda12 > rocm > vulkan > cpu) that the pinned runtime manifest publishes, so it can differ from `hardware.gpus[].accel` — an AMD box serves on `vulkan` while no ROCm build is published. Absent for the mock runtime. */
            runtime_accel?: string;
            stats: components["schemas"]["Stats"];
            memory: components["schemas"]["Memory"];
            disk: components["schemas"]["Disk"];
            /** @description Present once the first version check has completed. */
            update?: components["schemas"]["Update"];
        };
        /** @description Model memory on this node. `used_mb` is the measured footprint of every loaded runtime (physical footprint / proportional set size, not RSS, so mmap'd weight pages shared with the page cache are not double counted). `budget_mb` is what the daemon lets loaded models use in total before it unloads idle instances or declines a load. */
        Memory: {
            /** Format: int64 */
            used_mb: number;
            /** Format: int64 */
            budget_mb: number;
            /** Format: int64 */
            total_mb: number;
        };
        /** @description Model store usage. `models_bytes` counts complete artifacts, `partial_bytes` counts resumable `.partial` downloads, `budget_bytes` is `models.max_disk_mb` (0 = unlimited), `free_bytes` is free space on the volume holding the model directory. */
        Disk: {
            /** Format: int64 */
            models_bytes: number;
            /** Format: int64 */
            partial_bytes: number;
            /** Format: int64 */
            budget_bytes: number;
            /** Format: int64 */
            free_bytes: number;
            /** @description Absolute path of the model directory. */
            dir: string;
        };
        /** @description Result of the last version check against the mesh's version feed. `minimum` is the oldest daemon the coordinator still serves; below it the node is drained until updated. */
        Update: {
            available: boolean;
            current: string;
            latest: string;
            minimum?: string;
            below_minimum?: boolean;
            /** @description Release page / download for `latest`. */
            url?: string;
            /** Format: date-time */
            checked_at: string;
        };
        Hardware: {
            os: string;
            arch: string;
            cpu_model: string;
            /** Format: int64 */
            cpu_cores: number;
            /** Format: int64 */
            ram_mb: number;
            gpus: components["schemas"]["Gpu"][];
        };
        Gpu: {
            vendor: string;
            model: string;
            /** Format: int64 */
            vram_mb: number;
            accel: string;
            unified_memory: boolean;
        };
        Stats: {
            /** Format: double */
            tokens_per_sec_1m: number;
            /** Format: double */
            requests_per_min: number;
            /** Format: int64 */
            total_requests: number;
            /** Format: int64 */
            total_tokens: number;
            inflight: number;
            /** Format: int64 */
            earned_microcredits: number;
        };
        /**
         * @description What the request asks of the model.
         * @enum {string}
         */
        RequestKind: "chat" | "completion" | "embedding" | "decision";
        /**
         * @description Who asked. `local`: this machine's local API (`/v1/*`). `mesh`: a coordinator dispatch — a customer request or a canary; a node cannot tell the two apart, by design. `challenge`: a fingerprint challenge from the coordinator.
         * @enum {string}
         */
        RequestOrigin: "local" | "mesh" | "challenge";
        /**
         * @description `ok`: ran to completion. `cancelled`: stopped by the caller, the coordinator, a deadline or the governor (operator back at the machine). `invalid_input`: the runtime rejected the input itself (prompt over the model's context, too many options). `error`: anything else.
         * @enum {string}
         */
        RequestOutcome: "ok" | "error" | "cancelled" | "invalid_input";
        /** @description A request a runtime is serving right now. No content. */
        InflightRequest: {
            /** @description Local to this daemon process (`r<counter>`); matches the `request_finished` event and the FinishedRequest row. */
            id: string;
            model: string;
            kind: components["schemas"]["RequestKind"];
            origin: components["schemas"]["RequestOrigin"];
            /** Format: date-time */
            started_at: string;
            /** Format: int64 */
            elapsed_ms: number;
            /** @description Tokens generated so far (reasoning included). Always 0 for embeddings and decisions, which generate nothing. */
            tokens: number;
        };
        /** @description A request that ended. No content. */
        FinishedRequest: {
            id: string;
            model: string;
            kind: components["schemas"]["RequestKind"];
            origin: components["schemas"]["RequestOrigin"];
            /** Format: date-time */
            started_at: string;
            /** Format: int64 */
            duration_ms: number;
            /** @description 0 when the runtime reported no usage (cancelled, failed). */
            prompt_tokens: number;
            /** @description Generated tokens: the runtime's usage figure, or the count streamed before a cancellation. 0 for embeddings and decisions. */
            completion_tokens: number;
            outcome: components["schemas"]["RequestOutcome"];
        };
        /** @description One loaded model, and what it is doing. */
        ModelActivity: {
            model: string;
            /**
             * @description What the model is for (catalog flags).
             * @enum {string}
             */
            kind: "chat" | "embedding" | "decision";
            /** @description Requests this model's runtime is serving right now. */
            inflight: number;
            /** @description The same, by RequestKind (only kinds that are in flight). */
            inflight_by_kind: {
                [key: string]: number;
            };
            /**
             * Format: date-time
             * @description When the most recent request started. Set the moment a request starts, so it is always present while `inflight` > 0; absent only when the model has served none since it was loaded.
             */
            last_request_at?: string;
            /**
             * Format: int64
             * @description Present while nothing is in flight: seconds since the last request started (since the load when there was none).
             */
            idle_seconds?: number;
        };
        /** @description Work on a model that uses the machine without a request: `loading` (a runtime starting: weights read into memory, GPU warm-up) or `downloading`. */
        ModelOperation: {
            model: string;
            /** @enum {string} */
            op: "loading" | "downloading";
            /**
             * Format: date-time
             * @description Present for `loading`.
             */
            started_at?: string;
            /**
             * Format: int64
             * @description Present for `downloading`.
             */
            received_bytes?: number;
            /**
             * Format: int64
             * @description Present for `downloading`.
             */
            total_bytes?: number;
        };
        /** @description The "now" summary carried by every Status. */
        NodeActivity: {
            /** @description Every loaded model, sorted by id. */
            models: components["schemas"]["ModelActivity"][];
            operations: components["schemas"]["ModelOperation"][];
        };
        RequestActivity: {
            /**
             * Format: date-time
             * @description The daemon's clock when the snapshot was taken.
             */
            now: string;
            models: components["schemas"]["ModelActivity"][];
            operations: components["schemas"]["ModelOperation"][];
            /** @description Oldest first. */
            inflight: components["schemas"]["InflightRequest"][];
            /** @description Newest first; at most 200 are kept. */
            recent: components["schemas"]["FinishedRequest"][];
        };
        ModelRow: {
            id: string;
            /** Format: int64 */
            size_bytes: number;
            pinned: boolean;
            /** Format: date-time */
            last_used: string;
            /** @description assigned | downloading | ready | missing. `assigned` is a coordinator placement queued behind other work (nothing on disk yet). `missing` means the index knows the model but its file is gone from disk (deleted outside the daemon); it no longer counts against the budget and loads re-download it. */
            state: string;
            loaded: boolean;
            default: boolean;
            /** @description Absolute artifact path; present when the file exists. */
            path?: string;
            /**
             * Format: int64
             * @description Measured memory footprint; present only while loaded.
             */
            loaded_mb?: number;
            /**
             * Format: date-time
             * @description Present while loaded and not serving; the daemon unloads the instance after `idle_unload_seconds` (default model exempt).
             */
            idle_since?: string;
            /** @description Who installed it: `operator` (you, via the app/CLI/config) or `mesh` (coordinator placement). The mesh can only evict its own; yours are never touched. */
            origin: string;
            /**
             * Format: int64
             * @description Live progress summed over every file of the artifact; present only while downloading.
             */
            received_bytes?: number;
            /** @description Files in the artifact: the GGUF shards of a sharded model plus its mmproj sidecar when it has one. Present only for such multi-file models (a plain single-file model omits it). They live in `<models dir>/<id>/` under their upstream names; `path` is the first shard. */
            parts_total?: number;
            /** @description How many of `parts_total` are downloaded and verified; present with it. Shards download one at a time, so the one in flight is `parts_done + 1`. */
            parts_done?: number;
            assignment?: components["schemas"]["Assignment"];
        };
        /** @description Coordinator placement status for this model, when the mesh asked for it. Failures and refusals stay visible for ten minutes. */
        Assignment: {
            /** @description assigned | downloading | ready | cached | declined | failed | evicted. `cached` is a mesh-placed model that is on disk but unloaded (idle unload or memory pressure); the coordinator re-sends the assignment to load it when demand returns. */
            state: string;
            /** Format: date-time */
            since: string;
            /** @description Why it was declined or failed. */
            error?: string;
        };
        ModelList: {
            models: components["schemas"]["ModelRow"][];
        };
        /** @description A catalog model merged with this node's local state. */
        CatalogEntry: {
            id: string;
            /** @description Human-readable name incl. quant ("Qwen3.8 27B · Q4_K_M") — show this, not the id: ids are ambiguous now that model lines carry point versions (qwen3-8b vs qwen3.8-27b). Optional: absent when the daemon's catalog predates the field. */
            display_name?: string;
            family: string;
            /** Format: double */
            params_b: number;
            quant: string;
            sha256: string;
            /** Format: int64 */
            min_vram_mb: number;
            /** Format: int64 */
            min_ram_mb: number;
            license: string;
            artifact_url: string;
            /** Format: int64 */
            size_bytes: number;
            payout_class: string;
            /** Format: int64 */
            context_length: number;
            embeddings: boolean;
            /** @description A typed decision model: served by `POST /v1/systemone`, never by the chat endpoints. Mutually exclusive with `embeddings`. */
            decision: boolean;
            installed: boolean;
            /** @description downloading | ready; present when the artifact is local. */
            state?: string;
            /**
             * Format: int64
             * @description Live progress summed over every file; present only while downloading.
             */
            received_bytes?: number;
            /**
             * Format: int64
             * @description What the download fetches in all — `size_bytes` plus the mmproj sidecar when there is one — the denominator for `received_bytes`. Present only while downloading.
             */
            total_bytes?: number;
            /** @description Files in the artifact (GGUF shards plus mmproj); present only for multi-file models. `size_bytes` is already their sum. */
            parts_total?: number;
            /** @description Files downloaded and verified so far; present while downloading a multi-file model. */
            parts_done?: number;
            loaded: boolean;
            default: boolean;
        };
        CatalogList: {
            models: components["schemas"]["CatalogEntry"][];
        };
        /** @description Earnings as this node knows them. `source: ledger` — the figures are the operator account's ledger position, pushed by the coordinator over the tunnel (every node of the operator together; settled = vested and redeemable, pending = in escrow until the canary window clears). `source: estimated` — no fresh ledger snapshot (standalone, not enrolled, or the tunnel has been down for two push intervals): a simulated figure from this node's own counters, labelled in `note`. The `*_credits` integer fields are ledger credits at `credits_per_usd`; the legacy `earned_credits` / `escrow_credits` doubles are those divided by 1e6. */
        Earnings: {
            /** @enum {string} */
            source: "ledger" | "estimated";
            /**
             * Format: date-time
             * @description When the coordinator read the ledger (ledger only).
             */
            as_of?: string;
            /**
             * Format: int64
             * @description Vested, redeemable balance (ledger only).
             */
            settled_credits?: number;
            /**
             * Format: int64
             * @description In escrow, vesting after the canary window (ledger only).
             */
            pending_credits?: number;
            /**
             * Format: int64
             * @description Payout credits earned since 00:00 UTC (ledger only).
             */
            earned_today_credits?: number;
            /**
             * Format: int64
             * @description Payout credits earned in the trailing seven days (ledger only).
             */
            earned_7d_credits?: number;
            /**
             * Format: int64
             * @description Payout credits earned since the account opened (ledger only).
             */
            lifetime_payout_credits?: number;
            /**
             * Format: int64
             * @description The coordinator's peg; dollars are credits divided by this (ledger only).
             */
            credits_per_usd?: number;
            /**
             * Format: date-time
             * @description When the oldest pending lot vests; absent with nothing pending.
             */
            next_vest_at?: string;
            /** Format: int64 */
            earned_microcredits: number;
            /** Format: double */
            earned_credits: number;
            /** Format: double */
            est_usd: number;
            /** Format: double */
            est_usd_per_day: number;
            /**
             * Format: int64
             * @description Always this node's own count, whatever the source.
             */
            lifetime_tokens: number;
            /** Format: double */
            escrow_credits: number;
            note: string;
        };
        /** @description The operator's settings. GET returns every field plus `settings` (metadata for each: tier, how a change is applied, default, range, configured vs effective value). PUT takes the same object: the six required fields always, any other field only when it changes (omitted = unchanged); `settings` is ignored on PUT. The whole PUT is validated before anything is applied. Values persist in `<data_dir>/limits.toml`, which overrides `config.toml`. */
        Limits: {
            /** @description always | idle-only | scheduled. When this machine serves the mesh. `idle-only`: only while you are away from the keyboard and mouse. `scheduled`: only inside the schedule windows. `always`: whenever it is on. */
            serve_policy: string;
            /** @description With `idle-only`, how long keyboard and mouse must be quiet before the node starts serving. 0 on PUT = unchanged. */
            idle_after_seconds: number;
            /** @description When you come back to the machine, how long a request in flight may run on before it is cancelled. 0 on PUT = unchanged. */
            yield_grace_seconds: number;
            /** @description Serve while running on battery power. */
            serve_on_battery: boolean;
            /**
             * Format: double
             * @description Pause serving above this temperature; 0 disables the check.
             */
            max_temp_celsius: number;
            /** @description Daily serving windows for serve_policy=scheduled, one per entry, each "HH:MM-HH:MM" in the node's local time on a 24-hour clock (the hour may be one or two digits, the minute must be two — Go's "15:04" layout). The end is exclusive: "09:00-17:00" serves 09:00 through 16:59. A start later than its end wraps overnight ("22:00-08:00"); "22:00-00:00" runs to midnight; a window whose start equals its end matches nothing, so a full day is ["00:00-12:00", "12:00-00:00"]. The same windows apply every day (there is no day-of-week syntax) and an empty list never serves. An entry the daemon can't parse fails the whole PUT with 400; reads return windows normalised to zero-padded "HH:MM-HH:MM". */
            schedule: string[];
            /** @description Let the mesh place models on this node (download, load, and evict what it placed) inside `models.max_disk_mb`, minus your pinned and excluded models. Off means the node serves only what you installed. Omitted on PUT = unchanged. */
            mesh_managed?: boolean;
            /**
             * Format: int64
             * @description Model store budget (`models.max_disk_mb`); 0 = unlimited. LRU eviction of unpinned models keeps the store under it. Omitted on PUT = unchanged.
             */
            max_disk_mb?: number;
            /** @description Evict unpinned models not used for this many days (0 = never). Omitted on PUT = unchanged. */
            retention_days?: number;
            /**
             * Format: int64
             * @description Memory budget for loaded models (`budget.max_ram_mb`); 0 = auto (about half of physical memory on unified-memory machines, the GPU budget on discrete GPUs). Omitted on PUT = unchanged.
             */
            max_ram_mb?: number;
            /** @description Unload a loaded model after this long without a request (0 = never; default model exempt). Omitted on PUT = unchanged. */
            idle_unload_seconds?: number;
            /** @description Most requests one model serves at once (`budget.max_concurrent`): the ceiling on a model's slots and on mesh dispatches to this node. 0 = auto (16 with a GPU or unified memory, 2 on CPU). Every slot holds its own context in memory, so fewer slots leave room for more models. Applied by restarting idle models; a busy one changes at its next load. Omitted on PUT = unchanged. */
            max_concurrent?: number;
            /** @description Largest context, in tokens, a single request gets (`runtime.max_context`); 0 = the model's own window. Memory per model grows with slots x context. 0, or 1024 and up. Applied like `max_concurrent`. Omitted on PUT = unchanged. */
            max_context?: number;
            /** @description Smallest context a request is given (`runtime.min_context`): when memory is short the node gives up slots before going below it. 0 = 8192; otherwise 256 and up, and not above `max_context`. Applied like `max_concurrent`. Omitted on PUT = unchanged. */
            min_context?: number;
            /** @description Pin every request's context to exactly this many tokens (`runtime.context_length`), for every model, decision models included; 0 = plan it from memory (recommended). 256 and up. Applied like `max_concurrent`. Omitted on PUT = unchanged. */
            context_length?: number;
            /** @description Share of GPU memory models may use (`budget.max_vram_percent`): sizes the automatic memory budget on discrete GPUs and how many layers are offloaded. Takes effect after a daemon restart. Omitted on PUT = unchanged. */
            max_vram_percent?: number;
            /** @description Model ids the mesh may never place on this node (`models.exclude`). Applies to the next placement; a model already placed stays until evicted. Omitted on PUT = unchanged. */
            exclude?: string[];
            /** @description Model loaded when the daemon starts (`models.default`); empty or `none` = load nothing and serve what the mesh places. Takes effect after a daemon restart (use `POST /api/v1/models/{id}/default` to switch now). Omitted on PUT = unchanged. */
            default_model?: string;
            /** @description Require the bearer token on the local inference routes (`/v1/*`) too (`local_api.require_auth_v1`). Off, any program on this machine can use the loaded models without a key. Applied immediately. Omitted on PUT = unchanged. */
            require_auth_v1?: boolean;
            /**
             * @description Daemon log verbosity (`log.level`). Takes effect after a daemon restart. Omitted on PUT = unchanged.
             * @enum {string}
             */
            log_level?: "debug" | "info" | "warn" | "error";
            /** @description One entry per field above, in display order: everything an app needs to render the setting. Returned by GET and PUT; ignored when sent. */
            readonly settings?: components["schemas"]["LimitSetting"][];
        };
        /** @description Metadata and current state of one Limits field. */
        LimitSetting: {
            /** @description The field's name in Limits (`max_concurrent`). */
            key: string;
            /** @description The same setting in config.toml (`budget.max_concurrent`). */
            config_key: string;
            /** @description Short label. */
            title: string;
            /** @description Help text (the field's description, in one paragraph). */
            description: string;
            /**
             * @description `common`: show by default. `advanced`: show under an Advanced section.
             * @enum {string}
             */
            tier: "common" | "advanced";
            /**
             * @description How the daemon applies a change. `live`: immediately. `reload`: by restarting the runtimes of idle loaded models right away; a model with a request in flight keeps its layout until its next load. `restart`: saved now, used from the next daemon start (`pending_restart` is true until then).
             * @enum {string}
             */
            apply: "live" | "reload" | "restart";
            /**
             * @description How to edit the value.
             * @enum {string}
             */
            type: "boolean" | "integer" | "number" | "string" | "enum" | "string_list";
            /** @description Unit of an integer or number: seconds, MB, tokens, days, percent, °C, slots. */
            unit?: string;
            /** @description Smallest accepted value (integer and number types). */
            min?: number;
            /** @description Largest accepted value; absent = unbounded. */
            max?: number;
            /** @description The accepted values of an `enum`. */
            options?: string[];
            /** @description What the value 0 means when it is special ("auto", "never", "unlimited"). */
            zero_means?: string;
            /** @description The built-in default (the value's own JSON type). */
            default: unknown;
            /** @description The value as set (config.toml, limits.toml or this API): what GET returns in the field itself. */
            configured: unknown;
            /** @description Present when the daemon is running with something other than `configured`: an `auto` (0) resolved for this machine (`max_concurrent` 0 -> 16), or the previous value of a `restart` setting whose change is pending. */
            effective?: unknown;
            /** @description A change is saved but the daemon must restart to use it. */
            pending_restart: boolean;
        };
        ActivityEvent: {
            /** Format: date-time */
            time: string;
            /** @description download_started | downloaded | download_failed | loaded | unloaded | evicted | declined | missing | update_available | assignment */
            kind: string;
            /** @description mesh | operator | daemon */
            actor: string;
            model?: string;
            /** @description Human-readable one-liner for activity feeds. */
            message: string;
            /** @description Reason / error text when there is one. */
            detail?: string;
        };
        ActivityList: {
            events: components["schemas"]["ActivityEvent"][];
        };
        LogEntry: {
            /** Format: date-time */
            time: string;
            level: string;
            message: string;
            attrs?: string;
        };
        LogList: {
            logs: components["schemas"]["LogEntry"][];
        };
        PinRequest: {
            pinned: boolean;
        };
        DownloadStatus: {
            ok: boolean;
            /** @description downloading | ready */
            state: string;
        };
        EnrollRequest: {
            claim_code: string;
        };
        EnrollResponse: {
            ok: boolean;
            node_id: string;
            /** Format: date-time */
            cert_expires_at: string;
        };
        /** @description Free-form content given to the model: a string, an object or an array. A value that is not a string reaches the model as compact JSON text. */
        SystemOneJSON: string | {
            [key: string]: unknown;
        } | unknown[];
        /** @description The description of one `choice` option: free-form content, or `null` for an option that needs none. */
        SystemOneDescription: (string | {
            [key: string]: unknown;
        } | unknown[]) | null;
        SystemOneRequest: {
            /** @description Catalog id of a decision model (`decision: true`), or its `flock/<id>` alias. */
            model: string;
            /** @description The content to evaluate. */
            state: components["schemas"]["SystemOneJSON"];
            /** @description Maps a question id (yours) to a question. 1 to 64 entries, ids unique. Key order is preserved: answers come back in this order. */
            questions: {
                [key: string]: components["schemas"]["SystemOneQuestion"];
            };
        };
        /** @description One typed question, discriminated by `type`. */
        SystemOneQuestion: components["schemas"]["SystemOneChoiceQuestion"] | components["schemas"]["SystemOneScoreQuestion"] | components["schemas"]["SystemOneNoulQuestion"];
        /** @description Pick one of the labelled options. */
        SystemOneChoiceQuestion: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "choice";
            /** @description The question. Must not be empty. */
            instructions: components["schemas"]["SystemOneJSON"];
            /** @description Maps each option key to its description (or `null`). 2 to 255 options, keys unique; the model reads them in the order written. The model may have a lower limit of its own (`422`). */
            criteria: {
                [key: string]: components["schemas"]["SystemOneDescription"];
            };
        };
        /** @description Place the state on an ordered scale. */
        SystemOneScoreQuestion: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "score";
            /** @description The question. Must not be empty. */
            instructions: components["schemas"]["SystemOneJSON"];
            /** @description 2 to 10 level descriptions, lowest level first. */
            criteria: components["schemas"]["SystemOneJSON"][];
        };
        /** @description The probability that a yes/no statement is true. */
        SystemOneNoulQuestion: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "noul";
            /** @description The statement or question. Must not be empty. */
            instructions: components["schemas"]["SystemOneJSON"];
            /** @description Optional. Exactly the descriptions of `true` and `false`. */
            criteria?: {
                true: components["schemas"]["SystemOneJSON"];
                false: components["schemas"]["SystemOneJSON"];
            };
        };
        SystemOneResponse: {
            /** @description The catalog id of the model that answered. */
            model: string;
            /** @description Maps each question id to its answer, in request order. */
            answers: {
                [key: string]: components["schemas"]["SystemOneAnswer"];
            };
            usage: components["schemas"]["SystemOneUsage"];
        };
        /** @description One typed answer, discriminated by `type` (the question's type). */
        SystemOneAnswer: components["schemas"]["SystemOneChoiceAnswer"] | components["schemas"]["SystemOneScoreAnswer"] | components["schemas"]["SystemOneNoulAnswer"];
        SystemOneChoiceAnswer: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "choice";
            /** @description The option key with the highest probability. */
            choice: string;
            /** @description The probability of each option, in the order of the question's `criteria`; they sum to 1. */
            probabilities: {
                [key: string]: number;
            };
            /**
             * Format: double
             * @description 0 to 1; 0 means all options are equally likely.
             */
            confidence: number;
        };
        SystemOneScoreAnswer: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "score";
            /**
             * Format: double
             * @description The expected level index, weighted by probability; it can fall between two levels.
             */
            score: number;
            /** @description The description of each level index (`"0"`, `"1"`, …), rebuilt from the request's `criteria`. */
            legend: {
                [key: string]: components["schemas"]["SystemOneJSON"];
            };
            /** @description The probability of each level index, lowest first; they sum to 1. */
            probabilities: {
                [key: string]: number;
            };
            /**
             * Format: double
             * @description 0 to 1.
             */
            confidence: number;
        };
        SystemOneNoulAnswer: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "noul";
            /**
             * Format: double
             * @description The probability that the answer is true.
             */
            noul: number;
        };
        SystemOneUsage: {
            /** @description Prompt tokens across all questions. */
            input_tokens: number;
            /**
             * @description Always 0: a decision model generates no tokens.
             * @enum {integer}
             */
            output_tokens: 0;
        };
    };
    responses: {
        /** @description Success. */
        Ok: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Ok"];
            };
        };
        /** @description Missing or invalid bearer token. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unknown model or resource. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Malformed request. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Not available on this node (mock runtime, or standalone). */
        Unsupported: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description An upstream (catalog host, coordinator, runtime) failed. */
        Upstream: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Model id (catalog id or cache id). */
        ModelID: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Daemon is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current node status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getCatalog: {
        parameters: {
            query?: {
                /** @description Force a refetch instead of the cached copy (15 min TTL). */
                refresh?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Catalog entries with installed/loaded/default state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            501: components["responses"]["Unsupported"];
            502: components["responses"]["Upstream"];
        };
    };
    listModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cache contents merged with runtime state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    pinModel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Model id (catalog id or cache id). */
                id: components["parameters"]["ModelID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PinRequest"];
            };
        };
        responses: {
            200: components["responses"]["Ok"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            501: components["responses"]["Unsupported"];
        };
    };
    startModelDownload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Model id (catalog id or cache id). */
                id: components["parameters"]["ModelID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Already downloaded and verified. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadStatus"];
                };
            };
            /** @description Download running. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadStatus"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            501: components["responses"]["Unsupported"];
            502: components["responses"]["Upstream"];
        };
    };
    cancelModelDownload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Model id (catalog id or cache id). */
                id: components["parameters"]["ModelID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            501: components["responses"]["Unsupported"];
        };
    };
    loadModel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Model id (catalog id or cache id). */
                id: components["parameters"]["ModelID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            501: components["responses"]["Unsupported"];
            502: components["responses"]["Upstream"];
        };
    };
    unloadModel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Model id (catalog id or cache id). */
                id: components["parameters"]["ModelID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            501: components["responses"]["Unsupported"];
        };
    };
    setDefaultModel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Model id (catalog id or cache id). */
                id: components["parameters"]["ModelID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            501: components["responses"]["Unsupported"];
        };
    };
    deleteModel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Model id (catalog id or cache id). */
                id: components["parameters"]["ModelID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Ok"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            501: components["responses"]["Unsupported"];
        };
    };
    getEarnings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Earnings snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Earnings"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getLimits: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active limits. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Limits"];
                };
            };
            401: components["responses"]["Unauthorized"];
            501: components["responses"]["Unsupported"];
        };
    };
    updateLimits: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Limits"];
            };
        };
        responses: {
            /** @description The applied limits. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Limits"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            501: components["responses"]["Unsupported"];
        };
    };
    getLogs: {
        parameters: {
            query?: {
                /** @description Max entries to return (default 200). `limit` is an accepted alias. */
                n?: number;
                /** @description Alias for `n`. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Oldest-first log entries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    enrollNode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrollRequest"];
            };
        };
        responses: {
            /** @description Enrolled; the tunnel is running. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Another enrollment is already in progress. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            501: components["responses"]["Unsupported"];
            502: components["responses"]["Upstream"];
        };
    };
    getActivity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Activity rows. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getRequests: {
        parameters: {
            query?: {
                /** @description Max finished requests to return (default 50; 0 = none). */
                recent?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description In-flight and recent requests. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestActivity"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    checkUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Check result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Update"];
                };
            };
            401: components["responses"]["Unauthorized"];
            502: components["responses"]["Upstream"];
        };
    };
    getEvents: {
        parameters: {
            query?: {
                logs?: boolean;
                token?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    openaiListModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OpenAI `list` object of loaded models. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    openaiChatCompletions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Completion (or SSE stream when `stream: true`). Chat messages/deltas may carry `reasoning_content`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Unknown model, or a decision model (`error.code: model_not_found`, "model \"<id>\" is a decision model: use POST /v1/systemone"). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The governor refuses inference right now (state in the message). */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    openaiCompletions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Completion. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Unknown model, or a decision model (`error.code: model_not_found`, "model \"<id>\" is a decision model: use POST /v1/systemone"). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    openaiEmbeddings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Embeddings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Unknown model, or a decision model (`error.code: model_not_found`, "model \"<id>\" is a decision model: use POST /v1/systemone"). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    systemOne: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "model": "laya-q8_0",
                 *       "state": "Help! My payouts have been failing for 3 days.",
                 *       "questions": {
                 *         "department": {
                 *           "type": "choice",
                 *           "instructions": "Which team should handle this?",
                 *           "criteria": {
                 *             "billing": "Payments, invoicing, refunds",
                 *             "technical": null
                 *           }
                 *         },
                 *         "urgency": {
                 *           "type": "score",
                 *           "instructions": "How urgent is this?",
                 *           "criteria": [
                 *             "can wait",
                 *             "this week",
                 *             "today",
                 *             "right now"
                 *           ]
                 *         },
                 *         "escalate": {
                 *           "type": "noul",
                 *           "instructions": "Does this need a human within the hour?"
                 *         }
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["SystemOneRequest"];
            };
        };
        responses: {
            /** @description One typed answer per question, in request order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "model": "laya-q8_0",
                     *       "answers": {
                     *         "department": {
                     *           "type": "choice",
                     *           "choice": "billing",
                     *           "probabilities": {
                     *             "billing": 0.91,
                     *             "technical": 0.09
                     *           },
                     *           "confidence": 0.82
                     *         },
                     *         "urgency": {
                     *           "type": "score",
                     *           "score": 2.09,
                     *           "legend": {
                     *             "0": "can wait",
                     *             "1": "this week",
                     *             "2": "today",
                     *             "3": "right now"
                     *           },
                     *           "probabilities": {
                     *             "0": 0,
                     *             "1": 0.12,
                     *             "2": 0.67,
                     *             "3": 0.21
                     *           },
                     *           "confidence": 0.67
                     *         },
                     *         "escalate": {
                     *           "type": "noul",
                     *           "noul": 0.63
                     *         }
                     *       },
                     *       "usage": {
                     *         "input_tokens": 239,
                     *         "output_tokens": 0
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["SystemOneResponse"];
                };
            };
            /** @description The body is not a JSON object. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unknown model, or a model that is not a decision model (`error.code: model_not_found`; chat models are served by `/v1/chat/completions`). */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Validation failure (the message names the offending `questions.<id>` path), `images`, or input the runtime itself rejected (too many options for the model, a prompt over its context). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The runtime failed to answer. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The governor refuses inference right now (state in the message). */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
